version: "3"
services:
  nginx:
    depends_on:
      - gateway

    restart: always
    build: ./nginx
    ports:
      - '4050:80'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15671:15672"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    volumes:
      - /gateway/node_modules
    depends_on:
      - rabbitmq

  fibonacci:
    build: ./fibonacci
    volumes:
      - /fibonacci/node_modules
    depends_on:
      - rabbitmq

  factorial:
    build: ./factorial
    volumes:
      - /factorial/node_modules
    depends_on:
      - rabbitmq
